package com.lsz.persistence.product.mapper;

import com.lsz.persistence.product.dataobject.ProductInfoDO;
import com.lsz.persistence.product.dataobject.ProductInfoDOExample;
import java.util.List;

import com.lsz.product.ProductInfoQuery;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface ProductInfoDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spike_product
     *
     * @mbg.generated
     */
    long countByExample(ProductInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spike_product
     *
     * @mbg.generated
     */
    int deleteByExample(ProductInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spike_product
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spike_product
     *
     * @mbg.generated
     */
    int insert(ProductInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spike_product
     *
     * @mbg.generated
     */
    int insertSelective(ProductInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spike_product
     *
     * @mbg.generated
     */
    List<ProductInfoDO> selectByExampleWithRowbounds(ProductInfoDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spike_product
     *
     * @mbg.generated
     */
    List<ProductInfoDO> selectByExample(ProductInfoDOExample example);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spike_product
     *
     * @mbg.generated
     */
    List<ProductInfoDO> selectByCondition(ProductInfoQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spike_product
     *
     * @mbg.generated
     */
    ProductInfoDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spike_product
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ProductInfoDO record, @Param("example") ProductInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spike_product
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ProductInfoDO record, @Param("example") ProductInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spike_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ProductInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spike_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ProductInfoDO record);
}