package com.lsz.persistence.activity.dataobject;

import java.io.Serializable;

public class ActivityInfoDO implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spike_activity.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spike_activity.activity_id
     *
     * @mbg.generated
     */
    private Long activityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spike_activity.activity_name
     *
     * @mbg.generated
     */
    private String activityName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spike_activity.product_id
     *
     * @mbg.generated
     */
    private Long productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spike_activity.activity_start_time
     *
     * @mbg.generated
     */
    private Long activityStartTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spike_activity.activity_end_time
     *
     * @mbg.generated
     */
    private Long activityEndTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spike_activity.limit_num
     *
     * @mbg.generated
     */
    private Long limitNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spike_activity.stock_num
     *
     * @mbg.generated
     */
    private Long stockNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spike_activity.activity_status
     *
     * @mbg.generated
     */
    private String activityStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spike_activity.activity_picture_url
     *
     * @mbg.generated
     */
    private String activityPictureUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spike_activity.activity_price_amt
     *
     * @mbg.generated
     */
    private Long activityPriceAmt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spike_activity.ccy
     *
     * @mbg.generated
     */
    private String ccy;

    /**
     * 版本号
     */
    private Long casVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table spike_activity
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spike_activity.id
     *
     * @return the value of spike_activity.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spike_activity.id
     *
     * @param id the value for spike_activity.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spike_activity.activity_id
     *
     * @return the value of spike_activity.activity_id
     *
     * @mbg.generated
     */
    public Long getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spike_activity.activity_id
     *
     * @param activityId the value for spike_activity.activity_id
     *
     * @mbg.generated
     */
    public void setActivityId(Long activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spike_activity.activity_name
     *
     * @return the value of spike_activity.activity_name
     *
     * @mbg.generated
     */
    public String getActivityName() {
        return activityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spike_activity.activity_name
     *
     * @param activityName the value for spike_activity.activity_name
     *
     * @mbg.generated
     */
    public void setActivityName(String activityName) {
        this.activityName = activityName == null ? null : activityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spike_activity.product_id
     *
     * @return the value of spike_activity.product_id
     *
     * @mbg.generated
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spike_activity.product_id
     *
     * @param productId the value for spike_activity.product_id
     *
     * @mbg.generated
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spike_activity.activity_start_time
     *
     * @return the value of spike_activity.activity_start_time
     *
     * @mbg.generated
     */
    public Long getActivityStartTime() {
        return activityStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spike_activity.activity_start_time
     *
     * @param activityStartTime the value for spike_activity.activity_start_time
     *
     * @mbg.generated
     */
    public void setActivityStartTime(Long activityStartTime) {
        this.activityStartTime = activityStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spike_activity.activity_end_time
     *
     * @return the value of spike_activity.activity_end_time
     *
     * @mbg.generated
     */
    public Long getActivityEndTime() {
        return activityEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spike_activity.activity_end_time
     *
     * @param activityEndTime the value for spike_activity.activity_end_time
     *
     * @mbg.generated
     */
    public void setActivityEndTime(Long activityEndTime) {
        this.activityEndTime = activityEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spike_activity.limit_num
     *
     * @return the value of spike_activity.limit_num
     *
     * @mbg.generated
     */
    public Long getLimitNum() {
        return limitNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spike_activity.limit_num
     *
     * @param limitNum the value for spike_activity.limit_num
     *
     * @mbg.generated
     */
    public void setLimitNum(Long limitNum) {
        this.limitNum = limitNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spike_activity.stock_num
     *
     * @return the value of spike_activity.stock_num
     *
     * @mbg.generated
     */
    public Long getStockNum() {
        return stockNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spike_activity.stock_num
     *
     * @param stockNum the value for spike_activity.stock_num
     *
     * @mbg.generated
     */
    public void setStockNum(Long stockNum) {
        this.stockNum = stockNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spike_activity.activity_status
     *
     * @return the value of spike_activity.activity_status
     *
     * @mbg.generated
     */
    public String getActivityStatus() {
        return activityStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spike_activity.activity_status
     *
     * @param activityStatus the value for spike_activity.activity_status
     *
     * @mbg.generated
     */
    public void setActivityStatus(String activityStatus) {
        this.activityStatus = activityStatus == null ? null : activityStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spike_activity.activity_picture_url
     *
     * @return the value of spike_activity.activity_picture_url
     *
     * @mbg.generated
     */
    public String getActivityPictureUrl() {
        return activityPictureUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spike_activity.activity_picture_url
     *
     * @param activityPictureUrl the value for spike_activity.activity_picture_url
     *
     * @mbg.generated
     */
    public void setActivityPictureUrl(String activityPictureUrl) {
        this.activityPictureUrl = activityPictureUrl == null ? null : activityPictureUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spike_activity.activity_price_amt
     *
     * @return the value of spike_activity.activity_price_amt
     *
     * @mbg.generated
     */
    public Long getActivityPriceAmt() {
        return activityPriceAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spike_activity.activity_price_amt
     *
     * @param activityPriceAmt the value for spike_activity.activity_price_amt
     *
     * @mbg.generated
     */
    public void setActivityPriceAmt(Long activityPriceAmt) {
        this.activityPriceAmt = activityPriceAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spike_activity.ccy
     *
     * @return the value of spike_activity.ccy
     *
     * @mbg.generated
     */
    public String getCcy() {
        return ccy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spike_activity.ccy
     *
     * @param ccy the value for spike_activity.ccy
     *
     * @mbg.generated
     */
    public void setCcy(String ccy) {
        this.ccy = ccy == null ? null : ccy.trim();
    }

    public Long getCasVersion() {
        return casVersion;
    }

    public void setCasVersion(Long casVersion) {
        this.casVersion = casVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spike_activity
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ActivityInfoDO other = (ActivityInfoDO) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getActivityId() == null ? other.getActivityId() == null : this.getActivityId().equals(other.getActivityId()))
            && (this.getActivityName() == null ? other.getActivityName() == null : this.getActivityName().equals(other.getActivityName()))
            && (this.getProductId() == null ? other.getProductId() == null : this.getProductId().equals(other.getProductId()))
            && (this.getActivityStartTime() == null ? other.getActivityStartTime() == null : this.getActivityStartTime().equals(other.getActivityStartTime()))
            && (this.getActivityEndTime() == null ? other.getActivityEndTime() == null : this.getActivityEndTime().equals(other.getActivityEndTime()))
            && (this.getLimitNum() == null ? other.getLimitNum() == null : this.getLimitNum().equals(other.getLimitNum()))
            && (this.getStockNum() == null ? other.getStockNum() == null : this.getStockNum().equals(other.getStockNum()))
            && (this.getActivityStatus() == null ? other.getActivityStatus() == null : this.getActivityStatus().equals(other.getActivityStatus()))
            && (this.getActivityPictureUrl() == null ? other.getActivityPictureUrl() == null : this.getActivityPictureUrl().equals(other.getActivityPictureUrl()))
            && (this.getActivityPriceAmt() == null ? other.getActivityPriceAmt() == null : this.getActivityPriceAmt().equals(other.getActivityPriceAmt()))
            && (this.getCcy() == null ? other.getCcy() == null : this.getCcy().equals(other.getCcy()))
            && (this.getCasVersion() == null ? other.getCasVersion() == null : this.getCasVersion().equals(other.getCasVersion()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spike_activity
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getActivityId() == null) ? 0 : getActivityId().hashCode());
        result = prime * result + ((getActivityName() == null) ? 0 : getActivityName().hashCode());
        result = prime * result + ((getProductId() == null) ? 0 : getProductId().hashCode());
        result = prime * result + ((getActivityStartTime() == null) ? 0 : getActivityStartTime().hashCode());
        result = prime * result + ((getActivityEndTime() == null) ? 0 : getActivityEndTime().hashCode());
        result = prime * result + ((getLimitNum() == null) ? 0 : getLimitNum().hashCode());
        result = prime * result + ((getStockNum() == null) ? 0 : getStockNum().hashCode());
        result = prime * result + ((getActivityStatus() == null) ? 0 : getActivityStatus().hashCode());
        result = prime * result + ((getActivityPictureUrl() == null) ? 0 : getActivityPictureUrl().hashCode());
        result = prime * result + ((getActivityPriceAmt() == null) ? 0 : getActivityPriceAmt().hashCode());
        result = prime * result + ((getCcy() == null) ? 0 : getCcy().hashCode());
        result = prime * result + ((getCasVersion() == null) ? 0 : getCasVersion().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spike_activity
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", activityId=").append(activityId);
        sb.append(", activityName=").append(activityName);
        sb.append(", productId=").append(productId);
        sb.append(", activityStartTime=").append(activityStartTime);
        sb.append(", activityEndTime=").append(activityEndTime);
        sb.append(", limitNum=").append(limitNum);
        sb.append(", stockNum=").append(stockNum);
        sb.append(", activityStatus=").append(activityStatus);
        sb.append(", activityPictureUrl=").append(activityPictureUrl);
        sb.append(", activityPriceAmt=").append(activityPriceAmt);
        sb.append(", ccy=").append(ccy);
        sb.append(", casVersion=").append(casVersion);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}