package com.lsz.persistence.order;

import com.lsz.persistence.order.OrderRecordDO;
import com.lsz.persistence.order.OrderRecordDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface OrderRecordDOdMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spike_order
     *
     * @mbg.generated
     */
    long countByExample(OrderRecordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spike_order
     *
     * @mbg.generated
     */
    int deleteByExample(OrderRecordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spike_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spike_order
     *
     * @mbg.generated
     */
    int insert(OrderRecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spike_order
     *
     * @mbg.generated
     */
    int insertSelective(OrderRecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spike_order
     *
     * @mbg.generated
     */
    List<OrderRecordDO> selectByExampleWithRowbounds(OrderRecordDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spike_order
     *
     * @mbg.generated
     */
    List<OrderRecordDO> selectByExample(OrderRecordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spike_order
     *
     * @mbg.generated
     */
    OrderRecordDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spike_order
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") OrderRecordDO record, @Param("example") OrderRecordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spike_order
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") OrderRecordDO record, @Param("example") OrderRecordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spike_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(OrderRecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spike_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(OrderRecordDO record);
}